services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: localhost
      MONGO_INITDB_ROOT_PASSWORD: localhost
    volumes:
      - ./data/mongo/:/data/db/
