services:
  redis:
    image: redis/redis-stack
    container_name: redis_stack_container
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
