services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - 5672:5672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq
      - caddy
    labels:
      caddy: rabbitmq.localhost
      caddy.reverse_proxy: "{{upstreams 15672}}"
    restart: unless-stopped

networks:
  rabbitmq:
    driver: bridge
  caddy:
    external: true
